<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    https://my.studiopress.com/themes/genesis/
 */

 /* Template Name: Content Page */
 
//* This file handles pages, but only exists for the sake of child theme forward compatibility.


$pages = get_pages();
foreach ($pages as $page_data) {
    $content = apply_filters('the_content', $page_data->post_content);
    $title = $page_data->post_title;
    $slug = $page_data->post_name;
      if ($title != 'Contact' && $title != 'Contact Us' && $title != 'Blog' && $title != 'Content' && $title != 'Thank You' && $slug != 'contact' && $slug != 'contact-us' && $slug != 'blog' && $slug != 'content' && $slug != 'thank-you'){
      echo "<div class='$slug'>";
        echo "<h2>$title</h2>";
          $content = preg_replace('/<img[^>]+./','',$content);
          $content = preg_replace('/<input[^>]+./','',$content);
          $content = preg_replace('/<textarea[^>]+./','',$content);
          $content = preg_replace('/<radio[^>]+./','',$content);
          $content = preg_replace('/<select[^>]+./','',$content);
          echo preg_replace('/<iframe[^>]+./','',$content);
      echo "</div>";
  }
}



