<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    https://my.studiopress.com/themes/genesis/
 */

// add_action( 'genesis_after_header', 'genesis_do_search_title' );
remove_action( 'genesis_after_header', 'featured_title');
add_action( 'genesis_before_content', 'genesis_do_search_title');
//add_filter( 'genesis_entry_content', 'search_content');
add_action( 'genesis_before_content', 'search_before_content');
add_action( 'genesis_after_content', 'search_after_content', 9999);
add_action('wp_enqueue_scripts', 'queue_full_add');
function queue_full_add() {
  // .less file
  wp_enqueue_style( 'less-style-search', get_stylesheet_directory_uri() . '/views-styles/search-result-view.less' );
}

function search_before_content() {
  echo '<div class="search-right">';
  
  
  $searchImg = get_field('right_sidebar_image', 2235);
  
  
  if( !empty($searchImg) ){
			$searchImgStr = '<img src="'.$searchImg["url"].'" alt="'.$searchImg["alt"].'" />';
		}
  else{
    $searchImgStr = '';
  }
  echo '<div class="right-image">'.$searchImgStr.'</div>';
    if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('search-sidebar') );
  echo '</div>';
  echo '<div class="search-left">';
}
function search_after_content() {
  echo '</div>';
}

/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {
    echo '<div class="featured-area">';
          // featured image
      echo '<div class="reg-post-title"><div class="regular-post-title-wrap"><h1 class="reg-post-title">';
      $title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'genesis_search_title_text', __( 'Looking for:', 'genesis' ) ), get_search_query() );
      echo apply_filters( 'genesis_search_title_output', $title );
      echo '</h1></div></div>';
    echo '</div>';
}

genesis();
